/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import datos.Usuario;
import java.awt.Dimension;
import java.sql.Date;
import ui.Client.JClientes_ui;
import javax.swing.JOptionPane;
import ui.repair.JReparaciones_ui;
import ui.jorge.Tickets_ui;
import ui.mario_empleados.Empleado_ui;

/**
 *
 * @author REBOOTSYSTEM
 */
public class JAppmain_ui extends javax.swing.JFrame {

    public Usuario user = new Usuario();

    /**
     * Crea un nuevo formulario principal
     */
    public JAppmain_ui() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //dashboard();
    }

    JAppmain_ui(Usuario usuario) {
        initComponents();
        this.user = usuario;
        this.setExtendedState(MAXIMIZED_BOTH);
        setStatusBar();
        //dashboard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dskMain = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuReparaciones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuTitcketes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuUsuarios = new javax.swing.JMenuItem();
        mnuRoles = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación para Zapaterías Calzaditos");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/res/shoe.png")).getImage());
        setPreferredSize(new java.awt.Dimension(1024, 768));

        dskMain.setBackground(new java.awt.Color(255, 255, 255));
        dskMain.setAlignmentX(0.0F);
        dskMain.setAlignmentY(0.0F);

        javax.swing.GroupLayout dskMainLayout = new javax.swing.GroupLayout(dskMain);
        dskMain.setLayout(dskMainLayout);
        dskMainLayout.setHorizontalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        dskMainLayout.setVerticalGroup(
            dskMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        txtUser.setText("Usuario: ?");
        jPanel2.add(txtUser);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/shoe_black_32.png"))); // NOI18N
        jMenu1.setText("Archivo");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/user_24.png"))); // NOI18N
        mnuClientes.setMnemonic('c');
        mnuClientes.setText("Clientes");
        mnuClientes.setToolTipText("Presenta el formulario de clientes");
        mnuClientes.setSelected(true);
        mnuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuClientesMouseClicked(evt);
            }
        });
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClientes);
        mnuClientes.getAccessibleContext().setAccessibleParent(this);

        mnuReparaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnuReparaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/magic-wand_24.png"))); // NOI18N
        mnuReparaciones.setText("Reparaciones");
        mnuReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuReparacionesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuReparaciones);
        jMenu1.add(jSeparator1);

        mnuTitcketes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        mnuTitcketes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/printer_24.png"))); // NOI18N
        mnuTitcketes.setText("Ticketes");
        mnuTitcketes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTitcketesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTitcketes);
        jMenu1.add(jSeparator2);

        mnuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/cancel_24.png"))); // NOI18N
        mnuSalir.setMnemonic('s');
        mnuSalir.setText("Salir");
        mnuSalir.setToolTipText("Cerrar la aplicacion");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/settings_24.png"))); // NOI18N
        jMenu2.setText("Configuración");

        mnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/user_config_24.png"))); // NOI18N
        mnuUsuarios.setText("Empleados");
        mnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuUsuariosActionPerformed(evt);
            }
        });
        jMenu2.add(mnuUsuarios);

        mnuRoles.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.SHIFT_MASK));
        mnuRoles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/share_24.png"))); // NOI18N
        mnuRoles.setText("Roles");
        jMenu2.add(mnuRoles);
        jMenu2.add(jSeparator3);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/shoe_24.png"))); // NOI18N
        jMenuItem3.setText("Tipos de Calzado");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/info24.png"))); // NOI18N
        jMenu3.setText("Ayuda");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/speedometer24.png"))); // NOI18N
        jMenuItem2.setText("Dashboard");
        jMenu3.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/earth-globe24.png"))); // NOI18N
        jMenuItem1.setText("Acerca de");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskMain)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para el click del menu de clientes
     *
     * @param evt
     */
    private void mnuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuClientesMouseClicked

        try {
            JClientes_ui cliente_ui = new JClientes_ui(this);
            this.dskMain.add(cliente_ui);
            cliente_ui.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }

    }//GEN-LAST:event_mnuClientesMouseClicked

    /**
     * Evento para el click en el menu de clientes
     *
     * @param evt
     */
    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed

        if (evt.getSource().equals(this.mnuClientes)) {
            JClientes_ui cliente_ui = new JClientes_ui(this);
            cliente_ui.dskApp = this.dskMain;
            this.dskMain.add(cliente_ui);
            cliente_ui.show();
        }
        if (evt.getSource().equals(this.mnuSalir)) {
            this.setVisible(false);
            this.dispose();
        }

    }//GEN-LAST:event_mnuClientesActionPerformed

    /**
     * Evento del click en el menu de salir
     *
     * @param evt
     */

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        this.setVisible(false);
        // Libera la memoria de este objeto formulario
        this.dispose();
        // Vamonos... sale del aplicativo.
        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * Evento para el click en el menu de reparaciones
     *
     * @param evt
     */
    private void mnuReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuReparacionesActionPerformed
        try {
            JReparaciones_ui repara_ui = new JReparaciones_ui();
            repara_ui.dskApp = this.dskMain;
            this.dskMain.add(repara_ui);
            repara_ui.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_mnuReparacionesActionPerformed

    /**
     * Evento para el click en en menu de tickets
     *
     * @param evt
     */
    private void mnuTitcketesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTitcketesActionPerformed
        try {
            Tickets_ui tickets_ui = new Tickets_ui();

            this.dskMain.add(tickets_ui);
            tickets_ui.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_mnuTitcketesActionPerformed

    /**
     * Evento para el click en el menu de usuarios
     *
     * @param evt
     */
    private void mnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuUsuariosActionPerformed
        try {
            Empleado_ui empleado_ui = new Empleado_ui();

            this.dskMain.add(empleado_ui);
            empleado_ui.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_mnuUsuariosActionPerformed

    /**
     * Evento para el click en el menu de acerca de...
     *
     * @param evt
     */
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            JAbout about = new JAbout();
            this.dskMain.add(about);
            Dimension desktopSize = this.dskMain.getSize();
            Dimension FrameSize = about.getSize();
            about.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            about.show();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * Evento para el click en el menu de tipos de calzado.
     *
     * @param evt
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            jTipoCalzados tiposcalzados = new jTipoCalzados();
            this.dskMain.add(tiposcalzados);
            tiposcalzados.show();
        } catch (Exception e) {
            // Pos normalmente no se hace esto porque hay que atrapar los errores bien.
            e.printStackTrace();
        }


    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAppmain_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAppmain_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAppmain_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAppmain_ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAppmain_ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dskMain;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuReparaciones;
    private javax.swing.JMenuItem mnuRoles;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTitcketes;
    private javax.swing.JMenuItem mnuUsuarios;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables

    /**
     * Crea un dashboard para mostrar información
     */
    private void dashboard() {
        try {
            JDashboard_ui dash = new JDashboard_ui(this.dskMain, this);
            this.dskMain.add(dash);
            dash.setMaximum(true);
            dash.show();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * Crea una barra de estado
     */
    private void setStatusBar() {

        txtUser.setText("Usuario: " + user.getNombreCompleto());
    }
}
