/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import negocios.TiposCalzadoBL;

/**
 *
 * @author REBOOTSYSTEM
 */
public class jTipoCalzados extends javax.swing.JInternalFrame {

    private int tipoCalzadoId = 0;

    /**
     * Crea un nuevo formulario para los tipos de calzado.
     */
    public jTipoCalzados() {
        initComponents();
        // llenar los datos de la tabla
        fillTable();
        // Desactivar los botones
        disableButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        pmnuDelete = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtTipoCalzado = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTiposCalzados = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        pmnuDelete.setText("Eliminar");
        pmnuDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmnuDeleteActionPerformed(evt);
            }
        });
        popup.add(pmnuDelete);

        setClosable(true);
        setTitle("Tipos de Calzados");

        jLabel1.setText("Tipo de Calzado");

        btnAdd.setText("Agregar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblTiposCalzados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTiposCalzados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTiposCalzadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTiposCalzados);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/rubber_24.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTipoCalzado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTipoCalzado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento del click en el boton de agregar
     *
     * @param evt
     */
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Creamos el registro en la base de datos.
        // Utilizamos el create de la regla de negocios

        if (txtTipoCalzado.getText().length() > 0) // pues verificamos que tenga algo en el campo.
        {
            try {
                // Crear un tipo de calzado               
                TiposCalzadoBL.create(txtTipoCalzado.getText());
                // Llena los datos de la tabla
                fillTable();
                // Desactiva los botones
                disableButtons();
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error al crear un tipo de calzado " + e.getMessage());
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void pmnuDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmnuDeleteActionPerformed

        if (tipoCalzadoId > 0) {
            try {
                // Borrar un tipo de calzado
                TiposCalzadoBL.delete(tipoCalzadoId);
                
            } catch (Exception e) {
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_pmnuDeleteActionPerformed

    private void tblTiposCalzadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTiposCalzadosMouseClicked
        if (evt.isPopupTrigger()) {
            int row = this.tblTiposCalzados.getSelectedRow();
            //int row = tblTiposCalzados.rowAtPoint(evt.getPoint());
            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Seleccione una fila");

            } else {
                // Se apunta el id al tipo
                tipoCalzadoId = (int) this.tblTiposCalzados.getValueAt(row, 0);
                enabledButtons();
            }

            // if pointer is over a selected row, show popup
            if (tblTiposCalzados.isRowSelected(row)) {
                popup.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_tblTiposCalzadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem pmnuDelete;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JTable tblTiposCalzados;
    private javax.swing.JTextField txtTipoCalzado;
    // End of variables declaration//GEN-END:variables

    /**
     * Llena la tabla con los datos de la base de datos
     */
    private void fillTable() {
        try {
            DefaultTableModel modelTiposCalzados;

            modelTiposCalzados = TiposCalzadoBL.listar();

            this.tblTiposCalzados.setModel(modelTiposCalzados);
            TableColumnModel columnModel = tblTiposCalzados.getColumnModel();

            columnModel.getColumn(0).setPreferredWidth(30);
            columnModel.getColumn(1).setPreferredWidth(150);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al cargar la lista de tipos de calzados " + e.getMessage());
        }

    }

    private void disableButtons() {
        this.btnDelete.setEnabled(false);
    }
    
    private void enabledButtons()
    {
        btnDelete.setEnabled(true);
    }
}
